# Generated by Django 5.0.1 on 2025-01-08 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_referrals_made_profile_rewards_earned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='accounts.profile'),
        ),
    ]
