# Generated by Django 5.0.1 on 2025-01-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_services_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productscheme',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='services',
            name='product_id',
        ),
    ]
