# Generated by Django 5.0.1 on 2025-01-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_productscheme_product_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={},
        ),
        migrations.AddField(
            model_name='productscheme',
            name='product_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
