# Generated by Django 5.0.1 on 2025-01-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_services_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='product_id',
        ),
    ]
