# Generated by Django 5.0.1 on 2025-01-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_services_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productscheme',
            name='product_id',
        ),
    ]
