# Generated by Django 5.0.1 on 2025-01-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_productscheme_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscheme',
            name='product_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
